version: '3.8'

services:
  db:
    image: postgres:15
    container_name: melvad_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
#      - ./compose/postgres/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

#    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrator:
    container_name: melvad_db_mirtation
    env_file:
      - ./migrations/.env
    build:
      context: ./migrations
    depends_on:
      db:
        condition: service_healthy

  cache:
    container_name: melvad_cache
    image: redis:7.2.2
    env_file:
      - .env
    ports:
      - '6379:6379'

  app:
    container_name: melvad_app
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
      migrator:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
