version: '3.8'

services:
  db:
    image: postgres:15
    container_name: melvad_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
#      - ./compose/postgres/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

#    restart: unless-stopped
    ports:
      - "5432:5432"

  migrator:
    container_name: melvad_db_mirtation
    env_file:
      - dev.env
    build:
      context: .

  cache:
    container_name: melvad_cache
    image: redis:7.2.2
    env_file:
      - dev.env
    ports:
      - '6379:6379'
    hostname: localhost

  app:
    container_name: melvad_app
    env_file:
      - dev.env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
