DROP TABLE IF EXISTS users cascade;

create table users
(
    "id"                 bigint generated by default as identity primary key,
    "name"               text                                not null,
    "age"                int                                 not null
);

comment on table users is 'Список пользователей';
comment on column users.id is 'id пользователя';
comment on column users.name is 'Имя';
comment on column users.age is 'Возраст';
-- Задать индексы contraints

